// <auto-generated />
using API.Persistance.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace AirRangingAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210525003224_ResetAndUpdateValidation")]
    partial class ResetAndUpdateValidation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("API.Domain.Models.Aircraft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("AircraftType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CruiseSpeed")
                        .HasColumnType("integer");

                    b.Property<short>("EngineCount")
                        .HasColumnType("smallint");

                    b.Property<string>("EngineType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("FuelCapacity")
                        .HasColumnType("numeric");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IcaoId")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<string>("IcaoWakeCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("MaxRange")
                        .HasColumnType("numeric");

                    b.Property<int>("MaxTakeoffWeight")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Registration")
                        .HasColumnType("text");

                    b.Property<int>("ServiceCeiling")
                        .HasColumnType("integer");

                    b.Property<string>("Variant")
                        .HasColumnType("text");

                    b.Property<string>("WeightCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Aircrafts");

                    b.HasData(
                        new
                        {
                            Id = -100,
                            AircraftType = "SingleEngineLand",
                            CruiseSpeed = 107,
                            EngineCount = (short)1,
                            EngineType = "Piston",
                            FuelCapacity = 26m,
                            FuelType = "AvGas",
                            IcaoId = "C152",
                            IcaoWakeCategory = "Light",
                            Manufacturer = "Cessna",
                            MaxRange = 415m,
                            MaxTakeoffWeight = 1670,
                            Model = "152",
                            ServiceCeiling = 14700,
                            WeightCategory = "Small"
                        },
                        new
                        {
                            Id = -99,
                            AircraftType = "SingleEngineLand",
                            CruiseSpeed = 107,
                            EngineCount = (short)1,
                            EngineType = "Piston",
                            FuelCapacity = 38m,
                            FuelType = "AvGas",
                            IcaoId = "C152",
                            IcaoWakeCategory = "Light",
                            Manufacturer = "Cessna",
                            MaxRange = 691m,
                            MaxTakeoffWeight = 1670,
                            Model = "152",
                            ServiceCeiling = 14700,
                            Variant = "Long-Range",
                            WeightCategory = "Small"
                        },
                        new
                        {
                            Id = -98,
                            AircraftType = "SingleEngineLand",
                            CruiseSpeed = 122,
                            EngineCount = (short)1,
                            EngineType = "Piston",
                            FuelCapacity = 56m,
                            FuelType = "AvGas",
                            IcaoId = "C172",
                            IcaoWakeCategory = "Light",
                            Manufacturer = "Cessna",
                            MaxRange = 696m,
                            MaxTakeoffWeight = 2450,
                            Model = "172",
                            ServiceCeiling = 13500,
                            WeightCategory = "Small"
                        },
                        new
                        {
                            Id = -97,
                            AircraftType = "MultiEngineLand",
                            CruiseSpeed = 447,
                            EngineCount = (short)2,
                            EngineType = "Jet",
                            FuelCapacity = 6400m,
                            FuelType = "JetA",
                            IcaoId = "A320",
                            IcaoWakeCategory = "Medium",
                            Manufacturer = "Airbus",
                            MaxRange = 3300m,
                            MaxTakeoffWeight = 172000,
                            Model = "320",
                            ServiceCeiling = 39100,
                            WeightCategory = "Large"
                        },
                        new
                        {
                            Id = -96,
                            AircraftType = "MultiEngineLand",
                            CruiseSpeed = 453,
                            EngineCount = (short)2,
                            EngineType = "Jet",
                            FuelCapacity = 6875m,
                            FuelType = "JetA",
                            IcaoId = "B758",
                            IcaoWakeCategory = "Medium",
                            Manufacturer = "Boeing",
                            MaxRange = 2935m,
                            MaxTakeoffWeight = 144500,
                            Model = "737-800",
                            ServiceCeiling = 41000,
                            WeightCategory = "Large"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
