// <auto-generated />
using API.Persistance.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace AirRangingAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("API.Domain.Models.Aircraft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("AircraftType")
                        .HasColumnType("integer");

                    b.Property<int>("CruiseSpeed")
                        .HasColumnType("integer");

                    b.Property<int>("EngineType")
                        .HasColumnType("integer");

                    b.Property<decimal>("FuelCapacity")
                        .HasColumnType("numeric");

                    b.Property<int>("FuelType")
                        .HasColumnType("integer");

                    b.Property<string>("IcaoId")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<int>("IcaoWakeCategory")
                        .HasColumnType("integer");

                    b.Property<int>("MTOW")
                        .HasColumnType("integer");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("MaxRange")
                        .HasColumnType("numeric");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ServiceCeiling")
                        .HasColumnType("integer");

                    b.Property<string>("Variant")
                        .HasColumnType("text");

                    b.Property<int>("WeightCategory")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Aircrafts");

                    b.HasData(
                        new
                        {
                            Id = -100,
                            AircraftType = 1,
                            CruiseSpeed = 107,
                            EngineType = 1,
                            FuelCapacity = 26m,
                            FuelType = 0,
                            IcaoId = "C152",
                            IcaoWakeCategory = 2,
                            MTOW = 0,
                            Manufacturer = "Cessna",
                            MaxRange = 415m,
                            Model = "152",
                            ServiceCeiling = 14700,
                            WeightCategory = 3
                        },
                        new
                        {
                            Id = -99,
                            AircraftType = 1,
                            CruiseSpeed = 107,
                            EngineType = 1,
                            FuelCapacity = 38m,
                            FuelType = 0,
                            IcaoId = "C152",
                            IcaoWakeCategory = 2,
                            MTOW = 0,
                            Manufacturer = "Cessna",
                            MaxRange = 691m,
                            Model = "152",
                            ServiceCeiling = 14700,
                            Variant = "Long-Range",
                            WeightCategory = 3
                        },
                        new
                        {
                            Id = -98,
                            AircraftType = 1,
                            CruiseSpeed = 122,
                            EngineType = 1,
                            FuelCapacity = 56m,
                            FuelType = 0,
                            IcaoId = "C172",
                            IcaoWakeCategory = 2,
                            MTOW = 0,
                            Manufacturer = "Cessna",
                            MaxRange = 696m,
                            Model = "172",
                            ServiceCeiling = 13500,
                            WeightCategory = 3
                        },
                        new
                        {
                            Id = -97,
                            AircraftType = 1,
                            CruiseSpeed = 447,
                            EngineType = 3,
                            FuelCapacity = 6400m,
                            FuelType = 1,
                            IcaoId = "A320",
                            IcaoWakeCategory = 1,
                            MTOW = 172000,
                            Manufacturer = "Airbus",
                            MaxRange = 3300m,
                            Model = "320",
                            ServiceCeiling = 39100,
                            WeightCategory = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
